<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_semester-settings',
		'title' => 'Semester Settings',
		'fields' => array (
			array (
				'key' => 'field_57cd7d5e0af49',
				'label' => 'Semester',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cd771879ddc',
				'label' => 'Semester',
				'name' => 'acfmslaw_semester_list',
				'type' => 'repeater',
				'instructions' => 'Add New semester that will be displayed in multiple locaitons',
				'sub_fields' => array (
					array (
						'key' => 'field_57cd773a79ddd',
						'label' => 'Semester Period',
						'name' => 'acfmslaw_semester_period',
						'type' => 'text',
						'instructions' => 'Text that will be displayed in FrontPage Form and, if exits, in Open House Form',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57cd77bcc92d9',
						'label' => 'Display in Schedule Time Outline ',
						'name' => 'acfmslaw_display_in_schedule_time_outline_',
						'type' => 'true_false',
						'instructions' => 'Check this if you want do display this semester in Time Outline ( on FrontPage )',
						'column_width' => '',
						'message' => '',
						'default_value' => 0,
					),
					array (
						'key' => 'field_57cd77e4c92da',
						'label' => 'Schedule Time Outline Title',
						'name' => 'acfmslaw_schedule_time_outline_title',
						'type' => 'text',
						'instructions' => 'Text that appears on Time Outline as headline ( eq. Schedule for Fall 2016 )',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_57cd77bcc92d9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57cd782ec92db',
						'label' => 'Time Outline Dates',
						'name' => 'acfmslaw_time_outline_dates',
						'type' => 'repeater',
						'instructions' => 'Enter dates and other info. (Eq. Sept 13th 6:30 – 7:00 - Tours of the Building )',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_57cd77bcc92d9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_57cd7842c92dc',
								'label' => 'Time Outline Date',
								'name' => 'acfmslaw_time_outline_date',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Date',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Semester',
			),
			array (
				'key' => 'field_57cd7d680af4a',
				'label' => 'Open House',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57cd7e290af4b',
				'label' => 'Open House Dates',
				'name' => 'acfmslaw_open_house_dates',
				'type' => 'repeater',
				'instructions' => 'Insert Open House Dates',
				'sub_fields' => array (
					array (
						'key' => 'field_57cd7e440af4c',
						'label' => 'OH Date',
						'name' => 'acfmslaw_oh_date',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Date',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-general',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}